[build]
  command = "npm run build:ssg"
  publish = "dist"

# 启用Pretty URLs（默认启用，但显式声明确保尾部斜杠处理）
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "netlify-plugin-chromium"

# 添加MIME类型配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 确保JavaScript和TypeScript文件有正确的MIME类型
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# 重定向规则已移至 public/_redirects 文件

