[build]
  command = "npm run build:ssg"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-chromium"

# 添加MIME类型配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 确保JavaScript和TypeScript文件有正确的MIME类型
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# URL 重定向规则：将带斜杠的 URL 301 重定向到不带斜杠的版本
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
