[build]
  command = "npm run build:ssg"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-chromium"

# 添加MIME类型配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 确保JavaScript和TypeScript文件有正确的MIME类型
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# 重定向规则 - 统一管理所有URL重定向

# www重定向到non-www（强制重定向）
[[redirects]]
  from = "https://www.morse-coder.com/*"
  to = "https://morse-coder.com/:splat"
  status = 301
  force = true

# 将带斜杠的URL重定向到不带斜杠的版本
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# Legacy路径重定向
[[redirects]]
  from = "/encoders/txt-to-morse"
  to = "/decoders/txt-to-morse"
  status = 301

