name = "morse-debug-worker"
main = "src/index.js"
compatibility_date = "2024-07-30"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "morse-coder"

# Environment variables
[vars]
ALLOWED_ORIGINS = "https://morse-coder.com,http://localhost:5173,http://localhost:3000"
MAX_FILE_SIZE = "52428800"  # 50MB in bytes

# For production, set these as secrets using: wrangler secret put <name>
# [vars]
# R2_ACCESS_KEY_ID = "your-access-key"
# R2_SECRET_ACCESS_KEY = "your-secret-key"